### PR TITLE
Hide avoid standby mode feature on *nux OS

### LINKED ISSUE #3223: V1.1.6 "Avoid Standby Mode" does not work on Ubuntu 18
[How to Reproduce]

1.  Create a VM:  Ubuntu 18.04.3 LTS
	Kernel 5.0.0-27-generic 28~18.04.1-Ubuntu
	GNOME Shell 3.28.4 
	Apt update/upgrade should give you the same or more recent kernel & gnome versions.
	
2.  Open VM's Settings->Power->Automatic Suspend->Plugged In
	Set ON with Delay of 15 minutes.
	
3.  Install Bisq (w/ v1.1.6 test jar) and start an Arbitration client.
    Enable Settings -> "Avoid Stanby Mode".
    
4.  Don't touch anything for 15 minutes; watch Ubuntu 18 go into standby mode.

[Expected Results]

The Ubuntu 18 VM should not go into standby mode.

[Actual Results]

The Ubuntu 18 VM goes into standby mode.

### PR DESCRIPTION
**Pull request by ghubstan**
Displays standby mode button on only on Windows and OSX,
and hides it on Linux and Unix distributions.

TitledGroupBg num rows reduced to 7 when standby mode button
is not displayed.

Fixes #3223

Replaces PR #3322 -- rejected because source file reformat
rearanged class level field declarations, making review
more difficult.

### CODE REVIEW

**Comment by chimp1984** [comment]
We still enable it on Unix, no? See AvoidStandbyModeService

**Comment by ghubstan** [comment]
> We still enable it on Unix, no? See AvoidStandbyModeService

I see nothing in the issues or AvoidStandbyModeService src explicitly saying there are any problems with standby mode on Unix.  I had no good reason to assume standby mode won't work on Unix too, but I did.    

This PR would disable the feature on all flavors of Unix.  I can make sure the feature is not hidden on Unix.  Do you want me to do that?

**Comment by ripcurlx** [comment]
But don't we have a problem for all not Windows and macOS systems if that preference was already set to true? So the sound gets played and they are not able to deactivate it.

**Comment by ghubstan** [comment]
Closing and reopening PR to force travis-ci check.

File: desktop/src/main/java/bisq/desktop/main/settings/preferences/PreferencesView.java [hunk 1]
```diff
@@ -806,8 +811,10 @@ private void activateDisplayPreferences() {
 
         // We use opposite property (useStandbyMode) in preferences to have the default value (false) set as we want it,
         // so users who update gets set avoidStandbyMode=true (useStandbyMode=false)
-        avoidStandbyMode.setSelected(!preferences.isUseStandbyMode());
-        avoidStandbyMode.setOnAction(e -> preferences.setUseStandbyMode(!avoidStandbyMode.isSelected()));
+        if (displayStandbyModeFeature) {
+            avoidStandbyMode.setSelected(!preferences.isUseStandbyMode());
+            avoidStandbyMode.setOnAction(e -> preferences.setUseStandbyMode(!avoidStandbyMode.isSelected()));
+        }
```
Comment (freimair) [inline desktop/src/main/java/bisq/desktop/main/settings/preferences/PreferencesView.java:819]:
```suggestion
        } else {
            preferences.setUseStandbyMode(false)
        }
```

I agree with @ripcurlx, thus, the change suggestion. I believe that is a good place to put it. Instead of attaching a switch, we set it to false.

**Review by freimair — CHANGES_REQUESTED** [review]
other than that, I share the opinion of @wiz: Linux users have to disable sleep-mode on their own. Showing the switch on Linux promises something that does not work.

**Comment by chimp1984** [comment]
I think before changing behaviour we should be sure if the existing solution works on Linux and if it is needed as well if there is another better option to do it (e.g. via VM argument). 
To test this on OSX was pretty time consuming and difficult. As the result of the sleep mode behaviour can be that take offer attempts fail because the app is too slow to respond in time I think it is a rather serious issue which we only should change if we are sure to improve it. There have been only 1 or 2 people complaining about the sound (probably bad sound card produce artefacts) but before that fix we have many cases of failed take-offer attempts.

**Review by ripcurlx — APPROVED** [review]
ACK - it still runs as before on OSX (tested myself) and Windows and also removes this option on Linux. I agree that it is not good if we leave the user in the impression that this will prevent the application from going into standby mode, which seems to be not true as mentioned in https://github.com/bisq-network/bisq/issues/3223 .

**Review by freimair — APPROVED** [review]
