### PR TITLE
Warn that seeds are not a data backup

### LINKED ISSUE #4375: Improve warning about seeds are not a data backup.
### Description

A user formatted his computer saving only the seed and not the backup, while having open trades. As expected, he lost Bisq data and can't access locked and reserved funds.

#### Version

Any

### Steps to reproduce

This is user error, not a bug: remove Bisq data and restart Bisq only with seed while having open trades.

### Screenshots

wallet seed and backup

#### Additional info

To help preventing this user error, I request to display a pop-up warning **before** entering the password to display the seeds, showing the text inside the red square at the screenshot above `Please note that the seed words are NOT  a replacement for a backup. You need to create a backup... Importing seed words is only recommended for emergency cases. The application will not be functional without a proper backup of database files and keys!` 

It could be nice to add the wiki page https://bisq.wiki/Backing_up_application_data for extended info.

### PR DESCRIPTION
**Pull request by ghost**
Display a mandatory warning when the seed backup/restore screen is shown.  The warning informs the user that a data directory backup is necessary to restore the full state of bisq, not just the wallet seed words.

Fixes #4375

Screenshot:

image

### CODE REVIEW

File: desktop/src/main/java/bisq/desktop/main/account/content/seedwords/SeedWordsView.java [hunk 1]
```diff
@@ -163,7 +163,18 @@ public void activate() {
         seedWordsTextArea.getStyleClass().remove("validation-error");
         restoreDatePicker.getStyleClass().remove("validation-error");
 
+        new Popup().warning(Res.get("account.seed.backup.warning"))
+                .onAction(() -> {
+                    activatePartTwo();
```
Comment (ripcurlx) [inline desktop/src/main/java/bisq/desktop/main/account/content/seedwords/SeedWordsView.java]: Maybe you could make this more verbose. e.g.
```suggestion
                    showSeedPhrase();
```

File: desktop/src/main/java/bisq/desktop/main/account/content/seedwords/SeedWordsView.java [hunk 2]
```diff
@@ -163,7 +163,18 @@ public void activate() {
...
+                })
+                .actionButtonText(Res.get("shared.iUnderstand"))
+                .useIUnderstandButton()
+                .hideCloseButton()
+                .show();
 
+    }
+
+    public void activatePartTwo() {
```
Comment (ripcurlx) [inline desktop/src/main/java/bisq/desktop/main/account/content/seedwords/SeedWordsView.java]: Maybe you could make this more verbose. e.g. 
```suggestion
    public void showSeedPhrase() {
```

**Review by ripcurlx — CHANGES_REQUESTED** [review]
NACK - Just some minor code changes to make the refactoring more verbose. Besides that :+1:

**Comment by ghost** [comment]
Made the suggested review changes, and updated the popup to include a `Don't show again` checkbox.  See updated screenshot above.

**Review by ripcurlx — APPROVED** [review]
