### PR TITLE
Validate ignored peers and BTC nodes

### LINKED ISSUE #3137: Bisq does not validate Bitcoin P2P node at configuration time
[How to Reproduce]
1) Go to Settings -> Network
2) In the Bitcoin P2P node configuration under "use the following Bitcoin nodes", enter an invalid or unsupported hostname , such as the Tor v3 hostname 32zzibxmqi2ybxpqyggwwuwz7a3lbvtzoloti7cxoevyvijexvgsfeid.onion:8333
3) Bisq indicates it must be restarted, click OK

[Expected Results]
After Step 2, Bisq should validate the hostname is a valid Tor v2 hostname using regex or some other method, and also attempt to connect to this node. If it cannot validate or connect, it should not allow this setting to be changed, and it should not instruct the user to restart Bisq.
After Step 3, Bisq restarts, and despite the Bitcoin node being unreachable, the user should be able to proceed and reconfigure their settings to a reachable Bitcoin node.

[Actual Results]
After Step 2, Bisq did not perform any validation or testing of the user-entered hostname, it allowed the user the proceed, and it requested the user to proceed and restart Bisq.
After Step 3, Bisq restarts, but because the node is unreachable the following error is displayed and user is stuck with no way to correct their Bitcoin node settings, as they cannot get to the configuration screen.

Screen Shot 2019-08-25 at 16 38 49

### PR DESCRIPTION
**Pull request by devinbileck**
In addition to adding input validation for ignored peers and BTC nodes, this PR also fixes #3137.

Since with input validation the user is no longer able to enter an invalid BTC host, to verify #3137 start the app with the following option:
`--btcNodes=32zzibxmqi2ybxpqyggwwuwz7a3lbvtzoloti7cxoevyvijexvgsfeid.onion:8333`

You will be presented with the following:
image

After shutting down the app, restart it without the previous option and observe the BTC config. You will see the invalid custom BTC config but it will be using the provided BTC nodes.

image

### CODE REVIEW

**Review by sqrrm — APPROVED** [review]
ACK

It's good bisq can start to allow reconfig of btc nodes without it automatically connecting to the default nodes.

**Comment by wiz** [comment]
@devinbileck it seems your new input validation is too strict, totally valid FQDNs like `raspberrypi.local:8333` no longer work :sweat:

File: desktop/src/test/java/bisq/desktop/util/GUIUtilTest.java [hunk 1]
```diff
@@ -112,6 +116,33 @@ public void testOpenURLWithoutCampaignParameters() throws Exception {
...
+        assertTrue(regexValidator.validate("12.34.56.78:8888").isValid);
+
+        assertFalse(regexValidator.validate(" ").isValid);
+        assertFalse(regexValidator.validate("abcd.onion").isValid);
+        assertFalse(regexValidator.validate("abcdefghijklmnop,abcdefghijklmnop.onion").isValid);
+        assertFalse(regexValidator.validate("abcdefghi2345689.onion:9999").isValid);
+        assertFalse(regexValidator.validate("onion:9999,abcdefghijklmnop.onion:9999").isValid);
+        assertFalse(regexValidator.validate("abcdefghijklmnop.onion:").isValid);
+        assertFalse(regexValidator.validate("32zzibxmqi2ybxpqyggwwuwz7a3lbvtzoloti7cxoevyvijexvgsfeid.onion:8333").isValid);
+
```
Comment (wiz) [inline desktop/src/test/java/bisq/desktop/util/GUIUtilTest.java:141]:
```suggestion
        assertTrue(regexValidator.validate("example.com").isValid);
```

File: desktop/src/main/java/bisq/desktop/util/GUIUtil.java [hunk 2]
```diff
@@ -1107,4 +1108,14 @@ public static MaterialDesignIcon getIconForSignState(AccountAgeWitnessService.Si
                 state.equals(AccountAgeWitnessService.SignState.PEER_SIGNER)) ?
                 MaterialDesignIcon.APPROVAL : MaterialDesignIcon.ALERT_CIRCLE_OUTLINE;
     }
+
+    public static RegexValidator addressRegexValidator() {
+        RegexValidator regexValidator = new RegexValidator();
```
Comment (wiz) [inline desktop/src/main/java/bisq/desktop/util/GUIUtil.java:1113]: Missing the regex to validate `example.com` here?

**Comment by wiz** [comment]
Also need to handle IPv6 addresses, i.e. `[aaaa::bbbb]:8333` is a possible node address

**Comment by devinbileck** [comment]
Thanks. I will submit a PR shortly.
