### PR TITLE
Sorting order of offers appropriately by min/max range

### LINKED ISSUE #3818: Sorting order of offers
### Description

When sorting offers in the offer book by the second or third columns (amount in BTC and amount in the trade currency), the ones which have a MIN-MAX range are sorted only regarding the MAX AMOUNT.

But when I want to list the offers in **_`ASCENDING`_** order, I would like it to be done considering the MIN AMOUNT. The first one in the list should be the one which I can get/pay the least BTC or get/pay the least other currency.

#### Version

1.2.4

### Steps to reproduce

Sort the second or third columns in ascending order in open offers view.
For the descending order, it is fine, since it already considers the MAX amount.

### Expected behaviour

In ascending order, the MIN amount should be considered to sort the offers.

### Actual behaviour

It sorts the offers always per the MAX amount, which I consider wrong for the ascending order.

### Screenshots

image

#### Device or machine

Windows 10

#### Additional info

N/A

### PR DESCRIPTION
**Pull request by ghost**
Fixes #3818

This change fixes an issue with sorting the offer list when the amount is shown as a range.  The sort was hard coded on the top end of the range which does not make sense when sorting in ascending order.

In OfferBookView::activate() we add a listener for the sortTypeProperty on amountColumn and volumeColumn.  When the sortType is changed we set the comparator to be the approprate property of the Offer; either getAmount/getMinAmount; getVolume/getMinVolume.

### CODE REVIEW

File: desktop/src/main/java/bisq/desktop/main/offer/offerbook/OfferBookView.java [hunk 1]
```diff
@@ -293,6 +293,19 @@ protected void activate() {
...
+                amountColumn.setComparator(Comparator.comparing(o -> o.getOffer().getAmount(), Comparator.nullsFirst(Comparator.naturalOrder())));
+            else
+                amountColumn.setComparator(Comparator.comparing(o -> o.getOffer().getMinAmount(), Comparator.nullsFirst(Comparator.naturalOrder())));
+        });
+        volumeColumn.sortTypeProperty().addListener((observable, oldValue, newValue) -> {
+            if (newValue==TableColumn.SortType.DESCENDING)
+                volumeColumn.setComparator(Comparator.comparing(o -> o.getOffer().getVolume(), Comparator.nullsFirst(Comparator.naturalOrder())));
+            else
+                volumeColumn.setComparator(Comparator.comparing(o -> o.getOffer().getMinVolume(), Comparator.nullsFirst(Comparator.naturalOrder())));
+        });
```
Comment (ripcurlx) [inline desktop/src/main/java/bisq/desktop/main/offer/offerbook/OfferBookView.java]: As we had issues in the past concerning using no brackets for one line conditionals we decided to use always `{}`

Comment (ripcurlx) [inline desktop/src/main/java/bisq/desktop/main/offer/offerbook/OfferBookView.java]: And there should be spaces before and after `==`
```suggestion
        amountColumn.sortTypeProperty().addListener((observable, oldValue, newValue) -> {
            if (newValue == TableColumn.SortType.DESCENDING) {
                amountColumn.setComparator(Comparator.comparing(o -> o.getOffer().getAmount(), Comparator.nullsFirst(Comparator.naturalOrder())));
            } else {
                amountColumn.setComparator(Comparator.comparing(o -> o.getOffer().getMinAmount(), Comparator.nullsFirst(Comparator.naturalOrder())));
            }
        });
        volumeColumn.sortTypeProperty().addListener((observable, oldValue, newValue) -> {
            if (newValue == TableColumn.SortType.DESCENDING) {
                volumeColumn.setComparator(Comparator.comparing(o -> o.getOffer().getVolume(), Comparator.nullsFirst(Comparator.naturalOrder())));
            } else {
                volumeColumn.setComparator(Comparator.comparing(o -> o.getOffer().getMinVolume(), Comparator.nullsFirst(Comparator.naturalOrder())));
            }
        });
```

Comment (ripcurlx) [reply desktop/src/main/java/bisq/desktop/main/offer/offerbook/OfferBookView.java]: I'll have a look why Codacy is not checking for this.

**Review by ripcurlx — CHANGES_REQUESTED** [review]
NACK - based on my code format comments

ACK for functionality

**Review by ripcurlx — DISMISSED** [review]

**Comment by ripcurlx** [comment]
@jmacxx I just recognized that you haven't signed your commits.

**Comment by ripcurlx** [comment]
> Also make sure your commits are signed, and that you applied Bisq's code style and formatting.

**Review by ripcurlx — APPROVED** [review]
ACK

Testet it on Mainnet.
