### PR TITLE
Avoid that outdated donation and fee addresses are used.

### LINKED ISSUE #5762: Some BTC addresses utilized by Bisq are receiving both trade fees and time-locked deposits
### Description

Following discussion on Running the numbers of the Bisq DAO https://github.com/bisq-network/bisq/discussions/5171 and the subsequent discussions with other contributors a recent Bisq call. I thought it would be beneficial to open a separate issue to discuss the fact the some BTC addresses utilized by Bisq are receiving both trade fees and time-locked deposits.

Bisq utilizes BTC addresses to receive trade fees (for users not paying in BSQ) and to receive delayed payouts (time-locked deposits to a donation address) when either trader decides to send funds to arbitration. 

The addresses in current use can be seen here in a comment by @chimp1984 https://github.com/bisq-network/bisq/discussions/5171#discussioncomment-372304

Ideally, from an accounting / auditing perspective, Bisq would have addresses that only received either trade fees OR delayed payouts.

The issue with addresses receiving both trade fees AND delayed payouts is that it makes accounting / auditing more difficult.

### Version

1.7.4

### Steps to reproduce

Looking at all the addresses used by Bisq to receive trade fees and delayed payouts I compiled the following table. It appears that most addresses used by Bisq for this purpose receive both trade fees and time-locked deposits. 

| Address | Notes | Receiving trade fees | Receiving time-locked deposits | Last Active / Comments |
| ------------- | ------------- | ------------- | ------------- | ------------- |
| [1BVxNn3T12veSK6DgqwU4Hdn7QHcDDRag7](https://mempool.space/address/1BVxNn3T12veSK6DgqwU4Hdn7QHcDDRag7) | Default donation address  | Yes  | Yes  | April 2021, nit sure if this address has now been retired? |
| [3EtUWqsGThPtjwUczw27YCo6EWvQdaPUyp](https://mempool.space/address/3EtUWqsGThPtjwUczw27YCo6EWvQdaPUyp)  | burning2019 | Yes  | Yes | August 2021 - Sporadic use, not sure if due to people running old versions of Bisq? |
| [3A8Zc1XioE2HRzYfbb5P8iemCS72M6vRJV](https://mempool.space/address/3A8Zc1XioE2HRzYfbb5P8iemCS72M6vRJV)  | burningman2 | Yes | Yes | August 2021 - Sporadic use, not sure if due to people running old versions of Bisq? |
| [38bZBj5peYS3Husdz7AH3gEUiUbYRD951t](https://mempool.space/address/38bZBj5peYS3Husdz7AH3gEUiUbYRD951t)  | burningman3 | Yes | No | In constant use - I assume this is the main address for BTC trade fees. It is only receiving trade fees so this is good |
| [34VLFgtFKAtwTdZ5rengTT2g2zC99sWQLC](https://mempool.space/address/34VLFgtFKAtwTdZ5rengTT2g2zC99sWQLC)  | burningman3 | Yes | Yes | In constant use -  Mainly used as a donation address. Not sure why it is still receiving sporadic trade fees? |

### Expected behaviour

If possible the following addresses to be retired:

- 1BVxNn3T12veSK6DgqwU4Hdn7QHcDDRag7
- 3EtUWqsGThPtjwUczw27YCo6EWvQdaPUyp
- 3A8Zc1XioE2HRzYfbb5P8iemCS72M6vRJV

If possible the following address to receive no trade fees:

- 34VLFgtFKAtwTdZ5rengTT2g2zC99sWQLC

#### Additional info

If the above can be achieved would it be possible have a script or similar that could calculate:

- Trade fees received per month to 38bZBj5peYS3Husdz7AH3gEUiUbYRD951t
- Time locked deposit amounts per month sent to 34VLFgtFKAtwTdZ5rengTT2g2zC99sWQLC

Ideally the above would be included in the DAO charts:

dao

Failing the above a script or something similar to differentiate total trade fees vs total delayed payouts per calendar month, cycle, or year would be a useful tool for accounting / auditing.

### PR DESCRIPTION
**Pull request by chimp1984**
Fixes https://github.com/bisq-network/bisq/issues/5762

In case we get an outdated donation address (RECIPIENT_BTC_ADDRESS)
we trigger a dao resync. The user get a popup for doing a restart
in that case.
For the fee address selection we do not fall back to the
RECIPIENT_BTC_ADDRESS in case no address from filter is provided
but we use the hard coded address of the current fee receiver address.

### CODE REVIEW

**Comment by ghost** [comment]
Could be good to define the hardcoded addresses in `Config.java` since they are used in more than one place, and to avoid having them sprinkled through the code, 
see: `Param.java, DaoFacade.java, DelayedPayoutAddressProvider.java, TxValidatorTest.java`

---

    public static final String TESTNET_DONATION_ADDRESS = "2N4mVTpUZAnhm9phnxB7VrHB4aBhnWrcUrV";
    public static final String REGTEST_DONATION_ADDRESS = "2MzBNTJDjjXgViKBGnatDU3yWkJ8pJkEg9w";
    public static final String INITIAL_DONATION_ADDRESS = "1BVxNn3T12veSK6DgqwU4Hdn7QHcDDRag7";
    public static final String LATEST_DONATION_ADDRESS = "38bZBj5peYS3Husdz7AH3gEUiUbYRD951t";
    public static final String BURNINGMAN_2019 = "3EtUWqsGThPtjwUczw27YCo6EWvQdaPUyp";
    public static final String BURNINGMAN_2 = "3A8Zc1XioE2HRzYfbb5P8iemCS72M6vRJV";
    public static final String BURNINGMAN_3 = "34VLFgtFKAtwTdZ5rengTT2g2zC99sWQLC";

File: core/src/main/java/bisq/core/util/FeeReceiverSelector.java [hunk 1]
```diff
@@ -34,12 +32,16 @@
 
 @Slf4j
 public class FeeReceiverSelector {
-    public static String getAddress(DaoFacade daoFacade, FilterManager filterManager) {
-        return getAddress(daoFacade, filterManager, new Random());
+    public static String getMostRecentAddress() {
+        return "38bZBj5peYS3Husdz7AH3gEUiUbYRD951t";
```
Comment (ghost) [inline core/src/main/java/bisq/core/util/FeeReceiverSelector.java]: This fails when run in regtest, suggest something like this:

    public static String getMostRecentAddress() {
        return Config.baseCurrencyNetwork().isMainnet() ? Config.LATEST_DONATION_ADDRESS :  // mainnet
                Config.baseCurrencyNetwork().isDaoBetaNet() ? Config.LATEST_DONATION_ADDRESS : // daoBetaNet
                        Config.baseCurrencyNetwork().isTestnet() ? Config.TESTNET_DONATION_ADDRESS : // testnet
                                Config.REGTEST_DONATION_ADDRESS; // regtest
    }

**Review by ghost — CHANGES_REQUESTED** [review]

**Review by ripcurlx — DISMISSED** [review]
utACK

File: core/src/main/java/bisq/core/util/FeeReceiverSelector.java (hunk 1 above)
Comment (ripcurlx) [reply core/src/main/java/bisq/core/util/FeeReceiverSelector.java]: @chimp1984 Could you please respond to @jmacxx comment, before merging? Thanks!

**Comment by chimp1984** [comment]
> Could be good to define the hardcoded addresses in `Config.java` since they are used in more than one place, and to avoid having them sprinkled through the code, see: `Param.java, DaoFacade.java, DelayedPayoutAddressProvider.java, TxValidatorTest.java`
> 
> ```
> public static final String TESTNET_DONATION_ADDRESS = "2N4mVTpUZAnhm9phnxB7VrHB4aBhnWrcUrV";
> public static final String REGTEST_DONATION_ADDRESS = "2MzBNTJDjjXgViKBGnatDU3yWkJ8pJkEg9w";
> public static final String INITIAL_DONATION_ADDRESS = "1BVxNn3T12veSK6DgqwU4Hdn7QHcDDRag7";
> public static final String LATEST_DONATION_ADDRESS = "38bZBj5peYS3Husdz7AH3gEUiUbYRD951t";
> public static final String BURNINGMAN_2019 = "3EtUWqsGThPtjwUczw27YCo6EWvQdaPUyp";
> public static final String BURNINGMAN_2 = "3A8Zc1XioE2HRzYfbb5P8iemCS72M6vRJV";
> public static final String BURNINGMAN_3 = "34VLFgtFKAtwTdZ5rengTT2g2zC99sWQLC";
> ```

Yes agree. I will update that PR once the other PRs are merged...

File: core/src/main/java/bisq/core/util/FeeReceiverSelector.java (hunk 1 above)
Comment (chimp1984) [reply core/src/main/java/bisq/core/util/FeeReceiverSelector.java]: Ok. Will have a look once the other PRs are merged and that gets ready again...

**Review by ripcurlx — APPROVED** [review]
utACK
