### PR TITLE
Fix BankId leak

### LINKED ISSUE #5201: Bank id leaking
Hey guys 👋 
One of the strongest point of Bisq is to keep users’ info private and to show them just to the users who are involved in the trade.
However, if you pick randomly one buy btc SEPA offer and expand its details, you can see the bank id near the description of the payment method. Example: SEPA (XXXX)
This potentially lets everyone put the id online and find the bank where the creditor will get the payment.

Wouldn’t be better for privacy purposes to hide the bank id from the payment details and to show it just when you accept the offer?

### PR DESCRIPTION
**Pull request by BtcContributor**
Fixes #5201

Now BankId is no more displayed when a user requests details on the offer book.

### CODE REVIEW

**Review by wallclockbuilder — DISMISSED** [review]
ACK

File: desktop/src/main/java/bisq/desktop/main/overlays/windows/OfferDetailsWindow.java [hunk 1]
```diff
@@ -253,21 +253,20 @@ private void addContent() {
             addConfirmationLabelLabel(gridPane, ++rowIndex, Res.get("offerDetailsWindow.myTradingAccount"), myPaymentAccount.getAccountName());
         } else {
             final String method = Res.get(paymentMethod.getId());
-            String methodWithBankId = method + bankId;
             String paymentMethodLabel = Res.get("shared.paymentMethod");
             if (countryCode != null && (isNationalBanks || isSpecificBanks || isSepa)) {
```
Comment (ripcurlx) [inline desktop/src/main/java/bisq/desktop/main/overlays/windows/OfferDetailsWindow.java]: For specific banks payment method we do want to show the bank name and/or id as it would be otherwise for someone to match ones offer using this payment method.

File: desktop/src/main/java/bisq/desktop/main/overlays/windows/OfferDetailsWindow.java [hunk 2]
```diff
@@ -253,21 +253,20 @@ private void addContent() {
...
                 if (BankUtil.isBankIdRequired(countryCode))
                     addConfirmationLabelLabel(gridPane, ++rowIndex,
-                            paymentMethodLabel + " " + Res.get("offerDetailsWindow.offererBankId"),
```
Comment (ripcurlx) [inline desktop/src/main/java/bisq/desktop/main/overlays/windows/OfferDetailsWindow.java:261]: If you remove a translations please also remove it from `displayStrings.properties`. Otherwise we'll have more and more unnecessary strings to be translated. But in this case you probably need them anyways for the specific banks payment method

**Review by ripcurlx — CHANGES_REQUESTED** [review]
NACK - please see my comments.

**Comment by ripcurlx** [comment]
@pazza83 @BtcContributor This will remove the bank id and name from the offer details window, but of course for a sophisticated adversary this still can be accessed by code.

**Review by ripcurlx — APPROVED** [review]
utACK
