### PR TITLE
Wait for initialized wallet before processing dispute msgs, fix #2914

### LINKED ISSUE #2914: Nullpointer Exception while startup
Just starting (before entering passwd) I get the stack see attachement
[NullPointerWhileStart.txt](https://github.com/bisq-network/bisq/files/3316631/NullPointerWhileStart.txt)
After entering passwd app hangs in startscreen showing number of peers

### PR DESCRIPTION
**Pull request by sqrrm**

### CODE REVIEW

File: core/src/main/java/bisq/core/arbitration/DisputeManager.java [hunk 1]
```diff
@@ -266,6 +268,13 @@ private boolean isReadyForTxBroadcast() {
     }
 
     private void applyMessages() {
+        // Some messages can't be handled until all the services are properly initialized.
+        // In particular it's not possible to complete the signing of a dispute payout
+        // by an encrypted wallet until after it's been decrypted.
+        if (!servicesInitialized) {
+            return;
```
Comment (devinbileck) [inline core/src/main/java/bisq/core/arbitration/DisputeManager.java]: Just wondering if it would make more sense to put this check in tryApplyMessages? Since it appears to be the only caller of applyMessages and has an additional check.

**Review by devinbileck — APPROVED** [review]
utACK

File: core/src/main/java/bisq/core/arbitration/DisputeManager.java (hunk 1 above)
Comment (sqrrm) [reply core/src/main/java/bisq/core/arbitration/DisputeManager.java]: I moved to the readiness check, looks much more reasonable, thanks.

Comment (sqrrm) [reply core/src/main/java/bisq/core/arbitration/DisputeManager.java]: Please ack again if it looks good.

**Review by devinbileck — APPROVED** [review]
utACK
