### PR TITLE
Vote Reveal - Silent Fail

### LINKED ISSUE #3408: Vote Reveal - Silent Fail
I got this:

```
Oct-15 06:43:21.835 [JavaFX Application Thread] INFO  org.bitcoinj.wallet.Wallet: Completing send tx with 1 outputs totalling 0.00000596 BTC and a fee of 0.00 BTC/kB 
Oct-15 06:43:21.837 [JavaFX Application Thread] WARN  org.bitcoinj.wallet.Wallet: Insufficient value in wallet for send: needed 0.00001606 BTC more 
Oct-15 06:43:21.845 [JavaFX Application Thread] ERROR b.c.d.g.v.VoteRevealService: VoteRevealException{
     voteRevealTx=null,
     blindVoteTxId='3cf435e275b8e1518ea969fe90e0504bbed1d68135310b3c24546244fca90b5d',
     myVote=null
} bisq.core.dao.governance.votereveal.VoteRevealException: Exception at calling revealVote. 
Oct-15 06:43:24.448 [JavaFX Application Thread] INFO  b.c.d.m.DaoStateMonitoringService: Passed checkpoint Checkpoint {
     height=586920,
     hash=523aaad4e760f6ac6196fec1b3ec9a2f42e5b272
} 
```

Of course my BTC balance was vertically challenged  (euphemism for "too low"). If I didn't catch the exception in the logs, I would never have known there was an issue. Once I topped up, and on application restart, vote was published and information pop-up displayed.

I expected the earlier issue to have been reported with a pop-up as well.

I will fix it.

### PR DESCRIPTION
**Pull request by niyid**
Fixes #3408

The log below shows where the vote reveal failed silently as a result of insufficient wallet balance.
```
Oct-15 06:43:21.835 [JavaFX Application Thread] INFO  org.bitcoinj.wallet.Wallet: Completing send tx with 1 outputs totalling 0.00000596 BTC and a fee of 0.00 BTC/kB 
Oct-15 06:43:21.837 [JavaFX Application Thread] WARN  org.bitcoinj.wallet.Wallet: Insufficient value in wallet for send: needed 0.00001606 BTC more 
Oct-15 06:43:21.845 [JavaFX Application Thread] ERROR b.c.d.g.v.VoteRevealService: VoteRevealException{
     voteRevealTx=null,
     blindVoteTxId='3cf435e275b8e1518ea969fe90e0504bbed1d68135310b3c24546244fca90b5d',
     myVote=null
} bisq.core.dao.governance.votereveal.VoteRevealException: Exception at calling revealVote. 
Oct-15 06:43:24.448 [JavaFX Application Thread] INFO  b.c.d.m.DaoStateMonitoringService: Passed checkpoint Checkpoint {
     height=586920,
     hash=523aaad4e760f6ac6196fec1b3ec9a2f42e5b272
} 
```

### CODE REVIEW

**Comment by chimp1984** [comment]
Still relevant

**Comment by niyid** [comment]
> Still relevant

Great. Awaiting review.

File: core/src/main/java/bisq/core/dao/governance/votereveal/VoteRevealService.java [hunk 1]
```diff
@@ -252,6 +261,9 @@ private void revealVote(MyVote myVote, boolean isInVoteRevealPhase) {
         } catch (VoteRevealException e) {
             voteRevealExceptions.add(e);
         }
+
```
Comment (ripcurlx) [inline core/src/main/java/bisq/core/dao/governance/votereveal/VoteRevealService.java]: Unnecessary spaces that popped up when I auto-re-formatted your code.

**Review by ripcurlx — CHANGES_REQUESTED** [review]
NACK - Please see my comment. Would also be great if you could rebase your PR to master. Makes it easier for testing using the most up-to-date codebase.

File: core/src/main/java/bisq/core/dao/governance/votereveal/VoteRevealService.java [hunk 2]
```diff
@@ -83,15 +79,10 @@
...
-
     @Getter
     private final ObservableList<VoteRevealException> voteRevealExceptions = FXCollections.observableArrayList();
     private final List<VoteRevealTxPublishedListener> voteRevealTxPublishedListeners = new ArrayList<>();
-
-    ///////////////////////////////////////////////////////////////////////////////////////////
-    // Constructor
-    ///////////////////////////////////////////////////////////////////////////////////////////
-
+    private final List<VoteRevealTxFailedListener> voteRevealTxFailedListeners = new ArrayList<>();
```
Comment (ripcurlx) [inline core/src/main/java/bisq/core/dao/governance/votereveal/VoteRevealService.java]: NACK - You have to add  an empty line before the @Inject to apply our style guide.  I would have pushed this fix myself, but it seems to be that you are not allowing maintainers to push to your PR. Also please create a PR next time based on a separate branch and not directly from your master branch. Thanks!

**Review by ripcurlx — CHANGES_REQUESTED** [review]
NACK - Please see my comment

File: core/src/main/java/bisq/core/dao/governance/votereveal/VoteRevealService.java (hunk 2 above)
Comment (niyid) [reply core/src/main/java/bisq/core/dao/governance/votereveal/VoteRevealService.java]: Apologies. Even **`@Getter`** definition was affected. Fixed.

**Review by ripcurlx — CHANGES_REQUESTED** [review]
NACK

It does show it correctly when you start the app
Bildschirmfoto 2020-02-03 um 12 47 04
But it will show you now every time on startup without the chance of getting rid of it again.
I think it would be good to add a don't show again flag to this popup so the user can decide if he want to see the warning for this transaction vote reveal again.

**Review by ripcurlx — CHANGES_REQUESTED** [review]
NACK

Did you try this out?
That won't work. It still would be shown each time as you need to check if the key was set before you open the popup. Also we don't want to ask once and hide all popups afterwards, we want to show it at least once for each different transaction failure. So that means you need to extend the key with the tx id.

File: desktop/src/main/java/bisq/desktop/main/dao/DaoView.java [hunk 3]
```diff
@@ -75,10 +75,20 @@ private DaoView(CachingViewLoader viewLoader, VoteRevealService voteRevealServic
...
+
+        voteRevealService.addVoteRevealTxFailedListener((exception) -> {
+        	String key = "showVoteRevealFailedWarnPopupOnStartup" + exception.getBlindVoteTxId();
+        	if(preferences.showAgain(key)) {
+                new Popup().headLine(Res.get("dao.voteReveal.txFailed.headLine"))
+        		.dontShowAgainId(key)
+                .error(Res.get("dao.voteReveal.txFailed", exception.getBlindVoteTxId(), exception.getLocalizedMessage()))
+                .show();
+        	}
+        });
```
Comment (ripcurlx) [inline desktop/src/main/java/bisq/desktop/main/dao/DaoView.java]: Formatting broken

**Review by ripcurlx — CHANGES_REQUESTED** [review]
NACK

Formatting broken.

File: desktop/src/main/java/bisq/desktop/main/dao/DaoView.java (hunk 3 above)
Comment (niyid) [reply desktop/src/main/java/bisq/desktop/main/dao/DaoView.java]: Ah. Fixed.

**Review by ripcurlx — CHANGES_REQUESTED** [review]
NACK - I think you checked in some changes for .idea/codeStyles/Project.xml by mistake.

File: core/src/main/java/bisq/core/dao/governance/votereveal/VoteRevealService.java [hunk 4]
```diff
@@ -83,10 +79,12 @@
     private final BtcWalletService btcWalletService;
     private final P2PService p2PService;
     private final WalletsManager walletsManager;
-
+
```
Comment (ripcurlx) [inline core/src/main/java/bisq/core/dao/governance/votereveal/VoteRevealService.java]: No empty spaces

File: core/src/main/java/bisq/core/dao/governance/votereveal/VoteRevealService.java [hunk 5]
```diff
@@ -83,10 +79,12 @@
     private final BtcWalletService btcWalletService;
     private final P2PService p2PService;
     private final WalletsManager walletsManager;
-
+    
     @Getter
     private final ObservableList<VoteRevealException> voteRevealExceptions = FXCollections.observableArrayList();
     private final List<VoteRevealTxPublishedListener> voteRevealTxPublishedListeners = new ArrayList<>();
+    private final List<VoteRevealTxFailedListener> voteRevealTxFailedListeners = new ArrayList<>();
+
```
Comment (ripcurlx) [inline core/src/main/java/bisq/core/dao/governance/votereveal/VoteRevealService.java]: No empty spaces

File: desktop/src/main/java/bisq/desktop/main/dao/DaoView.java [hunk 6]
```diff
@@ -75,10 +75,20 @@ private DaoView(CachingViewLoader viewLoader, VoteRevealService voteRevealServic
...
         voteRevealService.addVoteRevealTxPublishedListener(txId -> {
-            new Popup<>().headLine(Res.get("dao.voteReveal.txPublished.headLine"))
+            new Popup().headLine(Res.get("dao.voteReveal.txPublished.headLine"))
                     .feedback(Res.get("dao.voteReveal.txPublished", txId))
                     .show();
         });
+
+        voteRevealService.addVoteRevealTxFailedListener((exception) -> {
+            String key = "showVoteRevealFailedWarnPopupOnStartup" + exception.getBlindVoteTxId();
+            if(preferences.showAgain(key)) {
```
Comment (ripcurlx) [inline desktop/src/main/java/bisq/desktop/main/dao/DaoView.java]: `if (preferences.showAgain(key)) {` whitespace is missing after `if`

**Review by ripcurlx — CHANGES_REQUESTED** [review]
NACK

Please see my comments. Also please rebase your PR so it is easier to test locally and I think it will remove one necessary change you did to the editorconfig file. Actually my checkstyle configuration should now catch this issues, but somehow running a recheck didn't do the trick yet.

**Review by ripcurlx — APPROVED** [review]
ACK

Tested it on local Regtest and it finally does what it is intended to do.

**Comment by sqrrm** [comment]
This PR touches core DAO code so it should be ACKed by manfred according to our merge rules.

**Comment by ripcurlx** [comment]
> This PR touches core DAO code so it should be ACKed by manfred according to our merge rules.

Not sure if a ACK by @ManfredKarrer is necessary in that case as it just surfaces an exception thrown during the vote reveal process. But in any case I mentioned now Manfred if he wants to give it an ACK as well.

**Comment by sqrrm** [comment]
I think sticking to this rule would be good.

**Comment by ripcurlx** [comment]
Ok - I'll ping @ManfredKarrer for an ACK.

**Comment by chimp1984** [comment]
NACK. See last comment. I would suggest to revert that PR and be more critical on dao package changes.
