### PR TITLE
[v1.5.5] Improve pending trades list rendering

### LINKED ISSUE #5144: [v1.5.5] Transferwise trading with old client throws NPE
### Description

- Old client created a buy offer with TransferWise and new client takes it
- After payment received is clicked NPE was thrown in new client.

```
Feb.-01 10:24:42.818 [JavaFX Application Thread] INFO  b.d.m.p.p.s.s.SellerStep3View: User pressed the [Confirm payment receipt] button for Trade ngkpxbc 
Feb.-01 10:24:42.818 [JavaFX Application Thread] INFO  b.c.t.p.FluentProtocol$Condition: We received a PAYMENT_RECEIVED event at phase FIAT_SENT and state SELLER_RECEIVED_FIAT_PAYMENT_INITIATED_MSG, tradeId=ngkpxbc-69f8f84c-1488-4d6e-aa1c-9e38a498ad6e-154 
Feb.-01 10:24:42.818 [JavaFX Application Thread] INFO  bisq.core.trade.Trade: Set new state at SellerAsTakerTrade (id=ngkpxbc): SELLER_CONFIRMED_IN_UI_FIAT_PAYMENT_RECEIPT 
Feb.-01 10:24:42.819 [JavaFX Application Thread] ERROR bisq.common.setup.CommonSetup: Uncaught Exception from thread JavaFX Application Thread 
Feb.-01 10:24:42.819 [JavaFX Application Thread] ERROR bisq.common.setup.CommonSetup: throwableMessage= null 
Feb.-01 10:24:42.819 [JavaFX Application Thread] ERROR bisq.common.setup.CommonSetup: throwableClass= class java.lang.NullPointerException 
Feb.-01 10:24:42.823 [JavaFX Application Thread] ERROR bisq.common.setup.CommonSetup: Stack trace:
java.lang.NullPointerException
	at bisq.desktop.main.portfolio.pendingtrades.PendingTradesView.isMaybeInvalidTrade(PendingTradesView.java:319)
	at bisq.desktop.main.portfolio.pendingtrades.PendingTradesView.access$100(PendingTradesView.java:105)
	at bisq.desktop.main.portfolio.pendingtrades.PendingTradesView$1$1.update(PendingTradesView.java:588)
	at bisq.desktop.main.portfolio.pendingtrades.PendingTradesView$1$1.lambda$updateItem$0(PendingTradesView.java:573)
```
Ignoring the NPE the trade still can be completed.

I wasn't able to re-produce this in this exact setup, but I think it might be worth to add a safe-guard.

### PR DESCRIPTION
**Pull request by ripcurlx**
Fixes #5144

### CODE REVIEW

File: desktop/src/main/java/bisq/desktop/main/portfolio/pendingtrades/PendingTradesView.java [hunk 1]
```diff
@@ -578,28 +576,32 @@ public void updateItem(final PendingTradesListItem item, boolean empty) {
...
                             private void update() {
                                 HyperlinkWithIcon field;
-                                if (isMaybeInvalidTrade(trade)) {
-                                    field = new HyperlinkWithIcon(trade.getShortId());
-                                    field.setIcon(FormBuilder.getMediumSizeIcon(MaterialDesignIcon.ALERT_CIRCLE_OUTLINE));
-                                    field.setOnAction(event -> tradeDetailsWindow.show(trade));
-                                    field.setTooltip(new Tooltip(Res.get("tooltip.invalidTradeState.warning")));
-                                    if (trade.isTxChainInvalid()) {
-                                        field.getIcon().getStyleClass().addAll("icon", "error-icon");
+                                if (trade != null) {
```
Comment (sqrrm) [inline desktop/src/main/java/bisq/desktop/main/portfolio/pendingtrades/PendingTradesView.java]: Prefer return early
`if (trade == null) return;`

Comment (ripcurlx) [reply desktop/src/main/java/bisq/desktop/main/portfolio/pendingtrades/PendingTradesView.java]: :+1:

**Review by sqrrm — APPROVED** [review]
utACK
