### PR TITLE
XMR autoconf should get amount from trade not offer

### LINKED ISSUE #4557: Monero auto-confirm fails with AMOUNT_NOT_MATCHING or NO_MATCH_FOUND in certain cases
### Description

The new Monero trade auto-confirm feature may fail if the XMR transaction is not yet confirmed at the time the BTC buyer presses "payment started" and submits the XMR proof of transaction data to BTC seller

#### Version

v1.3.9

### Steps to reproduce

1) Begin an XMR/BTC trade
2) After the buyer sends the XMR payment, submit the XMR proof of transaction before the XMR payment is confirmed by the Monero blockchain

### Expected behaviour

Bisq should retry after a while if the XMR transaction is not yet confirmed

### Actual behaviour

Bisq instantly fails the auto-confirm functionality, despite the XMR transaction getting confirmed shortly after

#### Additional info

```
Result{
     detail=Detail{
     numConfirmations=0,
     errorMsg='null'
} NO_MATCH_FOUND
} FAILED
```

```
This might not mean that the XMR transfer was invalid but you have to check yourself if the XMR transfer was correct. Result{
     detail=Detail{
     numConfirmations=0,
     errorMsg='null'
} AMOUNT_NOT_MATCHING
} FAILED
```

### PR DESCRIPTION
**Pull request by ghost**
* Get the amount from the trade rather than the offer.
* Log the expected amount when not matching the explorer result.  It would have made debugging this issue much more straightforward.

Fixes #4557

### CODE REVIEW

File: core/src/main/java/bisq/core/trade/txproof/xmr/XmrTxProofModel.java [hunk 1]
```diff
@@ -60,8 +60,7 @@
         this.serviceAddress = serviceAddress;
         this.autoConfirmSettings = autoConfirmSettings;
 
-        Coin tradeAmount = trade.getTradeAmount();
-        Volume volume = checkNotNull(trade.getOffer()).getVolumeByAmount(tradeAmount);
+        Volume volume = trade.getTradeVolume();
```
Comment (chimp1984) [inline core/src/main/java/bisq/core/trade/txproof/xmr/XmrTxProofModel.java:63]: Good catch. I think the trade price is the reason for the issue.

**Review by chimp1984 — APPROVED** [review]
utACK

Could you reproduce the issue that it was really caused by that?

**Comment by ghost** [comment]
Yes I reproduced the problem by forcing the taker's price to differ from maker's price same way as it was reported in the logs.  

I did not catch this problem during testing because all were self trades / same machine and so there was no price discrepancy between the trading parties.  Also I tended to use a fixed XMR rate which in hindsight was a bit silly as most traders use floating rates.

**Review by sqrrm — APPROVED** [review]
