### PR TITLE
Fix copy of BankName value + BranchId/BankId

### LINKED ISSUE #5200: Fix Bank transfer 'Copy BSB number' bug
### Steps to reproduce
- Take offer
- National Bank Transfer method
- Go to pay trader, open trade ID details
- Hit copy the :BSB code: number
- *Instead it copies the BANK NAME, not the BSB code/number

Most certainly first world problems I know, but is a small fix hopefully.

May be present on OTHER bank payment methods as well. 

image

### PR DESCRIPTION
**Pull request by BtcContributor**
Fixes #5200

This PR deals with cases like:
- BankName / BranchId (as the original issue)
- BankName / BankId

It would be trivial to add other instances if present.

### CODE REVIEW

File: desktop/src/main/java/bisq/desktop/util/FormBuilder.java [hunk 1]
```diff
@@ -1519,6 +1519,15 @@ private static Label getTopLabel(String title) {
         return addTopLabelTextFieldWithCopyIcon(gridPane, rowIndex, colIndex, title, value, -Layout.FLOATING_LABEL_DISTANCE);
     }
 
+    public static Tuple2<Label, TextFieldWithCopyIcon> addCompactTopLabelTextFieldWithCopyIcon(GridPane gridPane,
+                                                                                               int rowIndex,
+                                                                                               int colIndex,
+                                                                                               String title,
+                                                                                               String value,
+                                                                                               boolean withoutBeforeSlash) {
```
Comment (ripcurlx) [inline desktop/src/main/java/bisq/desktop/util/FormBuilder.java]: When used with code completion this naming `withoutBeforeSlash` is not very intuitive. Maybe rename it to `onlyCopyTextAfterDelimiter`

File: desktop/src/main/java/bisq/desktop/components/TextFieldWithCopyIcon.java [hunk 2]
```diff
@@ -39,7 +39,7 @@
     private final StringProperty text = new SimpleStringProperty();
     private final TextField textField;
     private boolean copyWithoutCurrencyPostFix;
-
+    private boolean copyWithoutBeforeSlash;
```
Comment (ripcurlx) [inline desktop/src/main/java/bisq/desktop/components/TextFieldWithCopyIcon.java]: As this code is independent of `/` I think it would be better to name it to `copyTextAfterDelimiter`

**Review by ripcurlx — CHANGES_REQUESTED** [review]
NACK - Please see my comments on the naming. Also for the future please have a look at https://chris.beams.io/posts/git-commit/. I'm not a great commit message writer myself, but I think there is some potential to grow :wink:

**Comment by BtcContributor** [comment]
Thanks for all the feedback @ripcurlx!

**Review by ripcurlx — APPROVED** [review]
utACK

**Review by Cha-cloud — COMMENTED** [review]
How do you connect your github and localbitcoins account together

**Comment by pazza83** [comment]
Hi @Cha-cloud not sure what you are trying to do but probably best to make a post on https://bisq.community/ or ask on [Keybase](https://keybase.io/team/bisq)
