### PR TITLE
(6/6) [BUGFIX] Fix duplicate sequence number use case (Non-persistent ProtectedStoragePayloads)

### LINKED ISSUE #3679: Attempting to create offer encounters error "There are no arbitrators available"
### Description

If you start a client after the arbitrator has shutdown their client, when you attempt to make an offer, you will encounter an error - "There are no arbitrators available".

#### Version

master (commit hash d12a4049ad423266f42b6987b8e4dc613c23684e)

### Steps to reproduce

Spin up a regtest environment:
- Start the seednodes
- Start the arbitrator instance and register as arbitrator, mediator, refund agent
- Start Alice
- Shut down Arbitrator
- Start Bob
- Attempt to create an offer with Alice
- Attempt to create an offer with Bob

### Expected behaviour

Both Alice and Bob should be able to proceed with creating an offer.

### Actual behaviour

Only Alice is able to proceed to the create offer view. Bob is presented with an error - "There are no arbitrators available".

### Screenshots

image

#### Device or machine

Windows 10

#### Additional info

From the log, it indicates there are no available disputeAgents but the connection details from the seed shows different.
```
#################################################################
Connected to node: localhost:3002
Received 3 instances
RefundAgent: 1
Mediator: 1
Arbitrator: 1
################################################################# 
Nov-24 17:21:43.488 [PeerGroup Thread] INFO  org.bitcoinj.core.PeerGroup: Attempting connection to [127.0.0.1]:18444     (0 connected, 1 pending, 0 max) 
Nov-24 17:21:43.522 [JavaFX Application Thread] INFO  b.n.p.p.g.RequestDataHandler: Processing 3 protectedStorageEntries took 42 ms. 
Nov-24 17:21:43.525 [JavaFX Application Thread] INFO  bisq.core.app.BisqSetup: walletInitialized=false, p2pNetWorkReady=true 
Nov-24 17:21:43.526 [JavaFX Application Thread] INFO  b.n.p.p.g.RequestDataHandler: Processing GetDataResponse took 48 ms 
Nov-24 17:21:43.542 [JavaFX Application Thread] INFO  bisq.core.app.BisqSetup: walletInitialized=true, p2pNetWorkReady=true 
Nov-24 17:21:43.543 [JavaFX Application Thread] INFO  bisq.core.app.BisqSetup: initDomainServices 
Nov-24 17:21:43.576 [JavaFX Application Thread] INFO  b.c.s.d.a.DisputeAgentManager: Available disputeAgents: [] 
Nov-24 17:21:43.577 [JavaFX Application Thread] INFO  b.c.s.d.a.DisputeAgentManager: Available disputeAgents: [] 
Nov-24 17:21:43.579 [JavaFX Application Thread] INFO  b.c.s.d.a.DisputeAgentManager: Available disputeAgents: [] 
```

### PR DESCRIPTION
**Pull request by julianknutsen**
Fixes: #3679

3d571c4

Fix a bug introduced in d484617385276d033223ad8f36e821504e116f96 that
did not properly handle a valid use case for duplicate sequence numbers.

For in-memory-only ProtectedStoragePayloads, the client nodes need a way
to reconstruct the Payloads after startup from peer and seed nodes. This
involves sending a ProtectedStorageEntry with a sequence number that
is equal to the last one the client had already seen.

This patch adds tests to confirm the bug and fix as well as the changes
necessary to allow adding of Payloads that were previously seen, but
removed during a restart.

### CODE REVIEW

File: p2p/src/test/java/bisq/network/p2p/storage/P2PDataStorageRemoveExpiredTest.java [hunk 1]
```diff
@@ -188,15 +188,5 @@ public void removeExpiredEntries_PurgeSeqNrMap() throws CryptoException, NoSuchA
         SavedTestState beforeState = this.testState.saveTestState(purgedProtectedStorageEntry);
         this.testState.mockedStorage.removeExpiredEntries();
         this.testState.verifyProtectedStorageRemove(beforeState, expectedRemoves, true, true, false, false, false);
-
```
Comment (julianknutsen) [inline p2p/src/test/java/bisq/network/p2p/storage/P2PDataStorageRemoveExpiredTest.java:185]: This test was testing too much when just calling verifyProtectedStorageRemove() gives us what we want. 

But, the failure did point out that we add expirable ProtectedStorageEntrys and then immediately expire them in the next expire cycle. I'll put this on my backlog to fix it. Not super urgent.

**Review by freimair — APPROVED** [review]
Ack

**Review by ripcurlx — APPROVED** [review]
utACK
