### PR TITLE
Fix issue with custom btc nodes

### LINKED ISSUE #1291: If user pass btc node per prg argument nr of min nodes is not correct
See:
https://bisq.community/t/bisq-not-connecting-to-my-full-node-and-connecting-to-a-remote-node-instead/4190/8

### PR DESCRIPTION
**Pull request by ManfredKarrer**
Fixes #1291

### CODE REVIEW

File: core/src/main/java/io/bisq/core/btc/wallet/WalletsSetup.java [hunk 1]
```diff
@@ -86,7 +86,7 @@
     private final BisqEnvironment bisqEnvironment;
     private final BitcoinNodes bitcoinNodes;
     private final int numConnectionForBtc;
-    private final boolean useAllProvidedNodes;
+    private boolean useAllProvidedNodes;
```
Comment (cbeams) [inline core/src/main/java/io/bisq/core/btc/wallet/WalletsSetup.java]: Sort mutable (non-final) fields after final fields so that the reader can more easily identify what's stateful and thus likely to be problematic.

File: core/src/main/java/io/bisq/core/btc/wallet/WalletsSetup.java [hunk 2]
```diff
@@ -300,35 +300,41 @@ private void configPeerNodesForLocalHostBitcoinNode() {
 
     private void configPeerNodes(Socks5Proxy socks5Proxy) {
         List<BitcoinNodes.BtcNode> btcNodeList = new ArrayList<>();
-        walletConfig.setMinBroadcastConnections((int) Math.floor(DEFAULT_CONNECTIONS * 0.8));
         switch (BitcoinNodes.BitcoinNodesOption.values()[preferences.getBitcoinNodesOptionOrdinal()]) {
             case CUSTOM:
-                String bitcoinNodesString = preferences.getBitcoinNodes();
-                if (bitcoinNodesString != null) {
+                final String bitcoinNodesString = preferences.getBitcoinNodes();
```
Comment (cbeams) [inline core/src/main/java/io/bisq/core/btc/wallet/WalletsSetup.java]: Not sure why the final modifier was added here. Generally, final should be omitted for local variables unless there's some special need (like use within a subsequent lambda expression). It's too noisy otherwise, and IIRC we haven't made a practice of using final on local variables elsewhere in Bisq.

File: core/src/main/java/io/bisq/core/btc/wallet/WalletsSetup.java [hunk 3]
```diff
@@ -300,35 +300,41 @@ private void configPeerNodesForLocalHostBitcoinNode() {
...
+                if (bitcoinNodesString != null && !bitcoinNodesString.isEmpty()) {
```
Comment (cbeams) [inline core/src/main/java/io/bisq/core/btc/wallet/WalletsSetup.java]: As far as I can tell, it is impossible for `bitcoinNodesString` to be empty. If the user provides `--btcNodes=""` at the command line, the empty string value gets rejected at command line option parsing time.

What the user *can* do is provide `--btcNodes=","`, which is effectively an empty list of nodes, but this logic doesn't capture it, because the raw `bitcoinNodesString` is literally `,`, and this is not an empty string. This leads to a bug where the list of custom nodes in the app is literally `,`, but Bisq still ends up connecting to the public network. I didn't track down exactly why that happens, because clearly this guard logic should be reworked anyway.

File: core/src/main/java/io/bisq/core/btc/wallet/WalletsSetup.java [hunk 4]
```diff
@@ -300,35 +300,41 @@ private void configPeerNodesForLocalHostBitcoinNode() {
...
                     btcNodeList = Splitter.on(",")
                             .splitToList(StringUtils.deleteWhitespace(bitcoinNodesString))
                             .stream()
                             .filter(e -> !e.isEmpty())
                             .map(BitcoinNodes.BtcNode::fromFullAddress)
                             .collect(Collectors.toList());
+                    walletConfig.setMinBroadcastConnections((int) Math.ceil(btcNodeList.size() * 0.5));
+                    // If Tor is set we usually only use onion nodes, but if user provides mixed clear net and onion nodes we want to use both
+                    useAllProvidedNodes = true;
```
Comment (cbeams) [inline core/src/main/java/io/bisq/core/btc/wallet/WalletsSetup.java]: It looks like the semantics of `useAllProvidedNodes` is getting overloaded here, because in this context, it really means "use all _custom_ nodes" that have been specified by the user at the command line. That'll be pretty confusing for anyone who doesn't have the context of this pull request.

It's also generally unfortunate to introduce this kind of mutability, but for a quick fix, at least consider changing the name to something like `useAllSpecifiedNodes`, so it at least catches the "provided" and "custom" cases equally.

File: core/src/main/java/io/bisq/core/btc/wallet/WalletsSetup.java [hunk 5]
```diff
@@ -300,35 +300,41 @@ private void configPeerNodesForLocalHostBitcoinNode() {
...
+                } else {
+                    log.warn("Custom nodes is set but no nodes are provided. We fall back to provided nodes option.");
+                    preferences.setBitcoinNodesOptionOrdinal(BitcoinNodes.BitcoinNodesOption.PROVIDED.ordinal());
+                    btcNodeList = bitcoinNodes.getProvidedBtcNodes();
+                    walletConfig.setMinBroadcastConnections(4);
                 }
                 break;
```
Comment (cbeams) [inline core/src/main/java/io/bisq/core/btc/wallet/WalletsSetup.java]: The `else` clause says we're going to "fall back" to the provided nodes option, and it then duplicates the code in the actual `PROVIDED` case block below. Why not remove the `break` statement here, move the `PUBLIC` case above this case, and let the logic here _actually_ fall though to the `PROVIDED` case below?

You can keep the `log.warn` statement, and `setBitcoinNodesOptionOrdinal` call, but the duplicate assignment of `btcNodeList` and call to `walletConfig.setMinBroadcastConnections` could be eliminated.

File: core/src/main/java/io/bisq/core/btc/wallet/WalletsSetup.java [hunk 6]
```diff
@@ -300,35 +300,41 @@ private void configPeerNodesForLocalHostBitcoinNode() {
...
                 // We require only 4 nodes instead of 7 (for 9 max connections) because our provided nodes
                 // are more reliable than random public nodes.
                 walletConfig.setMinBroadcastConnections(4);
                 break;
         }
 
-        final boolean useTorForBitcoinJ = socks5Proxy != null;
         List<PeerAddress> peerAddressList = new ArrayList<>();
-
+        boolean useTorForBitcoinJ = socks5Proxy != null;
```
Comment (cbeams) [inline core/src/main/java/io/bisq/core/btc/wallet/WalletsSetup.java]: Not sure why the `final` modifier was removed here or why the line was shifted around. Leaving it off is fine for reasons mentioned elsewhere, but this change threw me off, made me wonder if I was missing something.

**Review by cbeams — CHANGES_REQUESTED** [review]
NACK, see review comments.

File: core/src/main/java/io/bisq/core/btc/wallet/WalletsSetup.java (hunk 2 above)
Comment (ManfredKarrer) [reply core/src/main/java/io/bisq/core/btc/wallet/WalletsSetup.java]: Yes was leftover from earlier code where it was used in a lambda.

File: core/src/main/java/io/bisq/core/btc/wallet/WalletsSetup.java (hunk 3 above)
Comment (ManfredKarrer) [reply core/src/main/java/io/bisq/core/btc/wallet/WalletsSetup.java]: I preferred to not relay on the default value from the program arguments as this class does not know really about that.
The .filter(e -> !e.isEmpty()) should handle the case if we get a list of empty strings.
I improved the ocde via commit 9ac49bd91a2789e0db56d91a64b567a18bf9e951

Comment (ManfredKarrer) [reply core/src/main/java/io/bisq/core/btc/wallet/WalletsSetup.java]: Added a test as well.

File: core/src/main/java/io/bisq/core/btc/wallet/WalletsSetup.java (hunk 4 above)
Comment (ManfredKarrer) [reply core/src/main/java/io/bisq/core/btc/wallet/WalletsSetup.java]: I added a new flag.

File: core/src/main/java/io/bisq/core/btc/wallet/WalletsSetup.java (hunk 5 above)
Comment (ManfredKarrer) [reply core/src/main/java/io/bisq/core/btc/wallet/WalletsSetup.java]: Yes, another point I felt guilty as well ;-).
I refactored it in commit 83f7cfbd8b199a0006f4ea042fe3edb52e4b9cdb

I preferred to not alter the cases because I follow the convention to use the cases as they are defined in the enum and to use the default case at the end. Also IMO using the break for logical flows make the code harder to read/understand (its for me like return statements in the middle of the code which I try to prevent as well usually).

File: core/src/main/java/io/bisq/core/btc/wallet/WalletsSetup.java (hunk 6 above)
Comment (ManfredKarrer) [reply core/src/main/java/io/bisq/core/btc/wallet/WalletsSetup.java]: Was from a earlier code version where I altered the flag. I reverted it to final.

**Comment by ManfredKarrer** [comment]
@cbeams I changed all and it would be ready for another review round.

**Review by cbeams — APPROVED** [review]

**Comment by cbeams** [comment]
ACK, merging now.
