### PR TITLE
Revolut account should accept only phone number

### LINKED ISSUE #3728: Revolut account should be a phone number
### Description

I traded with people who had an email instead of a phone number in their revolut account.

I tested to create a new Revolut account in bisq. In the field "Phone number" I was able to put an email.

#### Version

1.2.3

### Steps to reproduce

Account => Add a new account => Revolut => Put an email

### Expected behaviour

When entering an email instead of a phone number, I should see an error message when trying to save.
Maybe limit the field to numbers, parenthesis and the + sign

### Actual behaviour

Email is accepted

#### Device or machine

Windows 10

### PR DESCRIPTION
**Pull request by beingindot**
Fixes #3728
Till now we used to accept email or phone number
Now we are accepting only phone number in input though
for display we will provide backward compatibility.

Based on the country selected, we will validate the given phone number input.

Added list of countries accepted from official revolut website
https://www.revolut.com/en-US/help/getting-started/verifying-identity/what-countries-are-supported

### CODE REVIEW

**Review by ripcurlx — CHANGES_REQUESTED** [review]
NACK

I tested it on Regtest and when switching the country in the combobox the validation is not updated. See screenshots below.

Bildschirmfoto 2019-12-12 um 15 42 54
When I switch the country to German the validation condition should be fulfilled, but is still showing the Austrian country code error message
Bildschirmfoto 2019-12-12 um 15 43 05

**Comment by beingindot** [comment]
Now I have added `updateAllInputsValid()` from combobox action event. that triggers validation and it enables save new account. 

but the error message around text field is not clearing on its own. only after we press tab it clears. I tried to use `accountIdInputTextField.resetValidation()` but not working so far. may be that's an existing bug? pls provide suggestions.

**Comment by ripcurlx** [comment]
> resetValidation

It has to be used similar as in the Bankform

```
holderNameInputTextField.resetValidation();
holderNameInputTextField.validate();
```

File: desktop/src/main/java/bisq/desktop/components/paymentmethods/RevolutForm.java [hunk 1]
```diff
@@ -84,6 +102,43 @@ public void addFormForAddAccount() {
...
+                return null;
+            }
+        });
+        return countryComboBox;
+    }
+
+    void setCountryComboBoxAction(ComboBox<Country> countryComboBox) {
+        countryComboBox.setOnAction(e -> {
+            selectedCountry = countryComboBox.getSelectionModel().getSelectedItem();
+            updateFromInputs();
```
Comment (ripcurlx) [inline desktop/src/main/java/bisq/desktop/components/paymentmethods/RevolutForm.java:140]: You need to reset the input field validation to make it work as expected. 
```
selectedCountry = countryComboBox.getSelectionModel().getSelectedItem();
accountIdInputTextField.resetValidation();
accountIdInputTextField.validate();
updateFromInputs();
```

Comment (beingindot) [reply desktop/src/main/java/bisq/desktop/components/paymentmethods/RevolutForm.java:140]: per your suggestion, added unfocus/refocus and this solved the problem. Pls check.

**Review by ripcurlx — APPROVED** [review]
ACK

Tested it on Regtest and it is working now as expected.
